#! /bin/bash

#There are N integers in an array A. All but one integer occur in pairs. Your task is to find the number that occurs only once.

#Input Format

#The first line of the input contains an integer N, indicating the number of integers. The next line contains N space-separated 
#integers that form the array A.

#Output Format

#Output S, the number that occurs only once.

declare -a numbers
read n
while IFS= read -r number || [[ -n "$number" ]]; do numbers+=($number); done
echo ${numbers[@]} | tr ' ' '\n' | sort | uniq -u | tr '\n' ' '
