#! /bin/bash

#Objective
#In this challenge, we practice reading and transforming arrays.

#Task
#You are given a list of countries, each on a new line. Your task is to read them into an array and then transform them in the following way:

#The first capital letter (if present) in each element of the array should be replaced with a dot ('.'). 
#Then, display the entire array with a space between each country's names.

#Input Format

#The input format consists of a list of country names each on a separate line. The only characters present in the 
#country names will be upper or lower case characters and hyphens.

#Output Format

#Transform the names as described and display the entire array of country names with a space between each of them. 

declare -a countries
while IFS= read -r country || [[ -n "$country" ]]; do countries+=($country); done
n_countries=${countries[@]/[A-Z]/.}
echo ${n_countries[@]}
