#! /bin/bash
#Given two integers, and , find their sum, difference, product, and quotient.
#Input Format: Two lines containing one integer each ( and , respectively).

read a; read b
echo $(( $a + $b ))
echo $(( $a - $b ))
echo $(( $a * $b ))
echo $(( $a / $b )) 
