#! /bin/bash

#Task

#Given an input file, in each line, highlight all the occurrences of 'thy' by wrapping them up in brace brackets. The search should be case-insensitive.

#Input Format

#A text file will be piped to your command via STDIN.

#Output Format

#Highlight all occurrences of 'thy' as shown in the example below. 

cat $1 | sed -e 's/thy/{&}/gi'
