#! /bin/bash

#Task

#Given n lines of credit card numbers, mask the first 12 digits of each credit card number with an asterisk (i.e., *) and print 
#the masked card number on a new line. Each credit card number consists of four space-separated groups of four digits. 
#For example, the credit card number 1234 5678 9101 1234 would be masked and printed as **** **** **** 1234.

#Input Format

#Each line contains a credit card number in the form dddd dddd dddd dddd, where d denotes a decimal digit 
#(i.e.,0 through 9). There are a total n of lines of credit card numbers.

#Output Format

#For each credit card number, print its masked version on a new line. 

cat $1 | sed -e 's/...[0-9] /**** /g'
